### ISSUE TITLE
Save Feature or Folder for Markdown Files in Windows

### ISSUE THREAD

**Issue by JoshMayberry** [kubernetes-retired/kui#9364]
I want to save my edited notebook.
It looks like there used to be a "Save" button in the file menu- but there is not any more.

I've tried using `File -> Open` to load a markdown file, but nothing happens.

It would be great if there was a folder I could save my markdown files in and they would be loaded into the system. (Like another option in the "Guidebooks" menu.

**Comment by JoshMayberry** [comment]
[kui-shell says](https://github.com/kui-shell/KuiNotebookBuilder#authoring-notebooks) we should be able to save markdown files in a `notebooks` folder- but I can not find any such folder in the pre-built windows program.

**Comment by JoshMayberry** [comment]
Could this [folder ](https://github.com/kui-shell/KuiClientTemplate/tree/main/plugins/plugin-client-notebooks/notebooks) be left exposed after an electron build is created?

If so, that would allow people to easily add notebooks without having to build the entire thing from source.

**Comment by rjackson64840** [comment]
I agree with Josh.  What will prevent me from using KUI is that it currently doesn't save my workspace and I have to start from scratch the next time I run the program.  I'm also on Windows.

**Comment by renannprado** [comment]
I thought I was too stupid to use the tool, but I'm glad I'm not the only one going through this.

It's impossible to save anything it seems. Even though in [this video](https://youtu.be/dqW4xROUaTs?t=1163) the guy saves it easily (without telling/showing now).

So sad, because it's cool tool, but unusable if one cannot create their own notebooks.
